# NumPy and SciPy

NumPy and SciPy are essential packages when you work in scientific projects and need n-dimensional arrays, special functions (e.g., the Bessel function, erf, etc.), constants as pi and the speed of light in vacuum.

For Matlab users, and for new NumPy/SciPy users there exists plenty of cheat sheets. One from [SciPy](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html), and another from [DataCamp (pdf)](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf).

# Installation
## Anaconda (Windows, macOS, Ubuntu)
In Anaconda it as easy as searching for the packages you want and select them for installation.

## macOS and Linux
Using the Python package manager, pip, you can install packages as follows:

```sh
pip3 install numpy scipy
```

## Including a package in Python
To use a package in Python one must import it, much like you would have to in e.g., Java or C/C++. The keyword to use is `import`. See below for examples for different ways of importing packages.

In [1]:
# The following will import NumPy and SciPy into the namespaces np and sp.
import numpy as np
import scipy as sp

# To use the functions in either package one types
print(np.pi)

3.141592653589793


In [2]:
# One can also only import specific functions if you wish
from numpy import linspace, sin

x = linspace(0, 2*np.pi, 3)
y = sin(x)

print(x)
print(y)

[0.         3.14159265 6.28318531]
[ 0.0000000e+00  1.2246468e-16 -2.4492936e-16]


In [3]:
# Working with numpy, it will return a numpy ndarray
print("'x' is of type {}\n'y' is of type {}".format(type(x), type(y)))

'x' is of type <class 'numpy.ndarray'>
'y' is of type <class 'numpy.ndarray'>


In [4]:
# Packages can have 'sub-packages'
import scipy.special as spe  # Import special functions like Bessel and erf

spe.erf(1.0 + 1j*2.3)  # The error function

(-13.210734622114826-9.6597984166347j)

In [5]:
# Import the speed of light in vacuum, and name it c0
from scipy.constants import c as c0

print(c0)

299792458.0


## Working with arrays

In [6]:
# To create arrays
a_array = np.array([1, 2, 3, 4], dtype=complex)

print(a_array)

# Matrix-like array with numpy
mtr_array = np.array([[1,2,3], [4,5,6]], dtype=float)
print(mtr_array)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
# np.random has all distributions of interest for us.
# randint(low, high, size=None)   It's not inclusive high, i.e., [low, high)
some_bits = np.random.randint(0, 2, size=8)   # Generate an array with 8 random integeres 0 or 1
other_bits = np.random.randint(0, 2, size=8)  # Generate an array with 8 random integeres 0 or 1

print('some_bits = {}'.format(some_bits))
print('other_bits = {}'.format(other_bits))

some_bits = [1 0 0 0 0 1 0 0]
other_bits = [0 0 1 0 0 1 0 1]


In [8]:
some_bits == other_bits

array([False,  True, False,  True,  True,  True,  True, False])

In [9]:
some_bits | other_bits

array([1, 0, 1, 0, 0, 1, 0, 1])

In [10]:
np.bitwise_and(some_bits, other_bits)

array([0, 0, 0, 0, 0, 1, 0, 0])

In [11]:
np.bitwise_or(some_bits, other_bits)

array([1, 0, 1, 0, 0, 1, 0, 1])

In [12]:
np.bitwise_xor(some_bits, other_bits)

array([1, 0, 1, 0, 0, 0, 0, 1])

The above arrays must not contain only 0 or 1, it can be any integer. Just as the bitwise operators in notebook 02.